---
title: "How do we process Lidar Data Today?"
description: "Bringing myselp up to speed on current processing"
date: 06-15-2025
date-modified: last-modified
---

## Seasons of Change - Seasons of Learning

Recently, I finished my PhD under the supervision of Dr. Nicholas Coops. Now, I am transitioning into post-doctoral role working with the Center for Wildfire Coexistence. I like to say I am crossing the boundary between wildfire recovery into wildfire mitigation and along the way I am completing my disaster cycle.

As a new post-doc I am reminded of my first year as a PhD - it is time to hit the ground and learn again! The last year has focused on ecology and writing. Now, I am turning back and brushing up on some of my more tecnical roots. Two of the technical subjects I am focusing on are wildfire hazard modeling and lidar data processing. The world of lidar processing has rapidly advanced and I others would appreciate me documenting my learnings here.

### In this blog-post I'll give an overview of the following topics 

-   What I mean when I say lidar data processing

-   What a general lidar processing workflow entails

-   packages and resouces that help you step through a lidar processing workflow

## Defining Lidar Data Processing

(more details to come)

## General Lidar Processing Workflow 

(more details to come)

## Resources + Packages to Process Lidar Data 

| Name | Reading and Converting LAS data | Chunked Reading | Classification | Parallization | Normalization | Rasterization | Language(s) | Cost |
|---------|-----------|----------|-------|-------|--------|-------|---------|-------|
| [laspy](https://laspy.readthedocs.io/en/latest/) | yes | yes | yes | no\* | no\* | no\* | Python | Free |
| [PDAL](https://pdal.io/en/stable/index.html) | yes | yes | yes | yes | no | yes | C++ (with python and Julia options) | Free |
| [lastools](https://lastools.github.io/) | yes | yes | yes | yes | yes | yes | DOS | Some aspects are free |
| [lidr](https://r-lidar.github.io/lidRbook/) | yes | yes | yes | yes | yes | yes | R | free |
| [rlas](https://github.com/r-lidar/rlas) | functions | automatically | called | by | lidr | package |  |  |
|  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |
